# This file was generated by GoReleaser. DO NOT EDIT.
cask "indexit" do
  preflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/indexit"]
    end
  end

  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "f1d0f0afbfccde5402831db707fef77d94ec2524cf9c9f0d6fb77e0115784afe"
      url "https://github.com/octopot/indexit/releases/download/v#{version}/indexit_#{version}_darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "673d08e2d325cd1e668b6165d783ef85d1fe25b066f10dc167b53200e4a5f9ce"
      url "https://github.com/octopot/indexit/releases/download/v#{version}/indexit_#{version}_darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cb8af8022bbd97aea8afebbcc0412d16e880e6945c8865f58230c9863e44d680"
      url "https://github.com/octopot/indexit/releases/download/v#{version}/indexit_#{version}_linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "c44ef04b92f46535aa840d4ece5ffad413731c5c98c0ecc6f5dff851fe049712"
      url "https://github.com/octopot/indexit/releases/download/v#{version}/indexit_#{version}_linux-amd64.tar.gz"
    end
  end

  name "indexit"
  desc "CLI for indexing personal data."
  homepage "https://github.com/octopot/indexit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "indexit"

  generate_completions_from_executable "indexit",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
