# This file was generated by GoReleaser. DO NOT EDIT.
cask "indexit" do
  preflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/indexit"]
    end
  end

  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "6423c7c71a348112215b03c71c0b98bae8e896f51b02d93c38b06d6e773405fa"
      url "https://github.com/octopot/indexit/releases/download/v#{version}/indexit_#{version}_darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "af0df7c9f674b53f96c2dd7444d65ee19ffff65300871de1b0f7312066f635a6"
      url "https://github.com/octopot/indexit/releases/download/v#{version}/indexit_#{version}_darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "69cc481236185af352ac67a1709ed96ce89eff85c92838f9488d9997df797b7f"
      url "https://github.com/octopot/indexit/releases/download/v#{version}/indexit_#{version}_linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "f9d47ddd0b61f3cebe4835d293a5226aa0165454b60325a87ee1cc9e265481cb"
      url "https://github.com/octopot/indexit/releases/download/v#{version}/indexit_#{version}_linux-amd64.tar.gz"
    end
  end

  name "indexit"
  desc "CLI for indexing personal data."
  homepage "https://github.com/octopot/indexit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "indexit"

  generate_completions_from_executable "indexit",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
