# This file was generated by GoReleaser. DO NOT EDIT.
cask "indexit" do
  preflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/indexit"]
    end
  end

  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "2124a358ac4cf3539305baf478d0f09adc242c5b6395aac1059ca5ef655246fa"
      url "https://github.com/octopot/indexit/releases/download/v#{version}/indexit_#{version}_darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "53eaed8e18dc7383de25a46d80976989a4e6b12f2fdd8f9e8e8b050db21e84bc"
      url "https://github.com/octopot/indexit/releases/download/v#{version}/indexit_#{version}_darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "55bd590a132f02663c308187f913cf2f5494a443de044d94e44bbc359ea59d2f"
      url "https://github.com/octopot/indexit/releases/download/v#{version}/indexit_#{version}_linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "626859ba9e016b039b265025fb08e0d5ca0e325148f5f3b79b58d0b581239c3a"
      url "https://github.com/octopot/indexit/releases/download/v#{version}/indexit_#{version}_linux-amd64.tar.gz"
    end
  end

  name "indexit"
  desc "CLI for indexing personal data."
  homepage "https://github.com/octopot/indexit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "indexit"

  generate_completions_from_executable "indexit",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
