# This file was generated by GoReleaser. DO NOT EDIT.
cask "maintainer" do
  preflight_steps do
    if_path_exists "opt/maintainer", base: :homebrew_prefix do
      warn "maintainer is installed as a formula; run `brew uninstall --formula maintainer` first"
    end
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/maintainer"]
    end
  end

  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "d9e63c275e52f0ec689b0e0bb6eb9f64c73ba4286e51fd358877a0ea6cd5f58d"
      url "https://github.com/octomation/maintainer/releases/download/v#{version}/maintainer_#{version}_darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "c439f9ddb2344a733eca57cae89f91ce5cd601060a180c0a78f3c86d77f48921"
      url "https://github.com/octomation/maintainer/releases/download/v#{version}/maintainer_#{version}_darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f805c3b145de0412694a40fa204fd70e77d3328da48fa20e1a759402b85cc3e4"
      url "https://github.com/octomation/maintainer/releases/download/v#{version}/maintainer_#{version}_linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "b5f17c209c4b7051aa8bb38e17547ad074ebf25f78f85868ef0625afe18a7e25"
      url "https://github.com/octomation/maintainer/releases/download/v#{version}/maintainer_#{version}_linux-amd64.tar.gz"
    end
  end

  name "maintainer"
  desc "Maintainer is an indispensable assistant to Open Source contribution."
  homepage "https://github.com/octomation/maintainer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "maintainer"

  generate_completions_from_executable "maintainer",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
