# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godownloader < Formula
  desc "This is the inverse of goreleaser. The goreleaser YAML file is read and
creates a custom shell script that can download the right package and
the right version for the existing machine.
"
  homepage "https://godownloader.octolab.org/"
  version "0.1.23"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kamilsk/godownloader/releases/download/v0.1.23/godownloader_0.1.23_darwin-arm64.tar.gz"
      sha256 "a44617b0621aa34a875a97f600f128e2db05e3279c473ce95005dbebc1c4c2dc"

      def install
        bin.install "godownloader"
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/godownloader/releases/download/v0.1.23/godownloader_0.1.23_darwin-amd64.tar.gz"
      sha256 "0ab76cd131fadc3fe7813971e417277244371caa6ea6379ebdffef6edc211987"

      def install
        bin.install "godownloader"
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamilsk/godownloader/releases/download/v0.1.23/godownloader_0.1.23_linux-arm64.tar.gz"
      sha256 "b790390e63997ce500e342505269ac98bfd2e59273f22ea78504c26e9f3902a4"

      def install
        bin.install "godownloader"
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/godownloader/releases/download/v0.1.23/godownloader_0.1.23_linux-amd64.tar.gz"
      sha256 "f4fe20fafbe601272b12978780aa3ca33130aab61004f3bc5e6bd50968df06d5"

      def install
        bin.install "godownloader"
        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/godownloader --version"
  end
end
