# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godownloader < Formula
  desc "This is the inverse of goreleaser. The goreleaser YAML file is read and
creates a custom shell script that can download the right package and
the right version for the existing machine.
"
  homepage "https://godownloader.octolab.org/"
  version "0.1.19"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kamilsk/godownloader/releases/download/v0.1.19/godownloader_0.1.19_darwin-arm64.tar.gz"
      sha256 "6d6ef57c173b3bae7096769123dbd45ea6e6a2f489ad4d393c74222d8193e102"

      def install
        bin.install "godownloader"
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/godownloader/releases/download/v0.1.19/godownloader_0.1.19_darwin-amd64.tar.gz"
      sha256 "cc62c229e1171f023879f9defcbbeafec835ee55da402fa8e727553604639326"

      def install
        bin.install "godownloader"
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamilsk/godownloader/releases/download/v0.1.19/godownloader_0.1.19_linux-arm64.tar.gz"
      sha256 "3cf27a5784dc316bf177e699f2305b6146081486e067a5e2cba1a248e028b93c"

      def install
        bin.install "godownloader"
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/godownloader/releases/download/v0.1.19/godownloader_0.1.19_linux-amd64.tar.gz"
      sha256 "6ad3df24a860812a5864d065e82a15886dd607282da725c41317b12eaca9ec86"

      def install
        bin.install "godownloader"
        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/godownloader --version"
  end
end
