# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godownloader < Formula
  desc "This is the inverse of goreleaser. The goreleaser YAML file is read and
creates a custom shell script that can download the right package and
the right version for the existing machine.
"
  homepage "https://godownloader.octolab.org/"
  version "0.1.17"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kamilsk/godownloader/releases/download/v0.1.17/godownloader_0.1.17_darwin-arm64.tar.gz"
      sha256 "aa283bd415ee09f536cb89e8d051629c51ee2677d4baf12e3a2d97223f9bbdbc"

      def install
        bin.install "godownloader"
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/godownloader/releases/download/v0.1.17/godownloader_0.1.17_darwin-amd64.tar.gz"
      sha256 "64d2e816f5b9bf31886f8f1a609165bab852d34fcd43ccf171953e519aa8e528"

      def install
        bin.install "godownloader"
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamilsk/godownloader/releases/download/v0.1.17/godownloader_0.1.17_linux-arm64.tar.gz"
      sha256 "15c459c0145672722a325913e275c7f436c82d44d539f2f6077e03116e88af3b"

      def install
        bin.install "godownloader"
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/godownloader/releases/download/v0.1.17/godownloader_0.1.17_linux-amd64.tar.gz"
      sha256 "8626eb6e6e4b7335cada84941b9a4f98fa43e93fb97c499571bc8610ff02d4f1"

      def install
        bin.install "godownloader"
        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/godownloader --version"
  end
end
