# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goimports < Formula
  desc "Command goimports updates your Go import lines,
adding missing ones and removing unreferenced ones.
In addition to fixing imports, goimports also formats
your code in the same style as gofmt so it can be used
as a replacement for your editor's gofmt-on-save hook.
"
  homepage "https://goimports.octolab.org/"
  version "0.19.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kamilsk/go-tools/releases/download/v0.19.0/goimports_0.19.0_darwin-arm64.tar.gz"
      sha256 "4da7aaab21c2d68e784e00804903a91b6fe7b72bb680b3c25930f146bbbc3afc"

      def install
        bin.install "goimports"
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/go-tools/releases/download/v0.19.0/goimports_0.19.0_darwin-amd64.tar.gz"
      sha256 "49380b17785733660cb42eee29f06fdbbefae95c0caaf5d4c9ef1e65f76b7aa7"

      def install
        bin.install "goimports"
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamilsk/go-tools/releases/download/v0.19.0/goimports_0.19.0_linux-arm64.tar.gz"
      sha256 "597d5fcadcd92271475de48d77bce57e7d35111f246c9f3ee60a7bf6e760b14b"

      def install
        bin.install "goimports"
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/go-tools/releases/download/v0.19.0/goimports_0.19.0_linux-amd64.tar.gz"
      sha256 "785bc569a5e54b7f6448529b4cdc8de498190d3862d762ed1b567cb247489995"

      def install
        bin.install "goimports"
        prefix.install_metafiles
      end
    end
  end
end
