# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GolangciLint < Formula
  desc "Fast linters runner for Go."
  homepage "https://github.com/kamilsk/golangci-lint"
  version "1.53.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kamilsk/golangci-lint/releases/download/v1.53.3/golangci-lint_1.53.3_darwin-arm64.tar.gz"
      sha256 "d5b170e9447dffc8beefc9c6f59faeaedac895c5235eba30a83dadc783cb10ac"

      def install
        bin.install "golangci-lint"

        output = Utils.popen_read("#{bin}/golangci-lint completion bash")
        (bash_completion/"golangci-lint").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion fish")
        (fish_completion/"golangci-lint.fish").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
        (zsh_completion/"_golangci-lint").write output

        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/golangci-lint/releases/download/v1.53.3/golangci-lint_1.53.3_darwin-amd64.tar.gz"
      sha256 "ceaf95e820bd150e22986db8537144690651de9436990aa852f6674261936340"

      def install
        bin.install "golangci-lint"

        output = Utils.popen_read("#{bin}/golangci-lint completion bash")
        (bash_completion/"golangci-lint").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion fish")
        (fish_completion/"golangci-lint.fish").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
        (zsh_completion/"_golangci-lint").write output

        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamilsk/golangci-lint/releases/download/v1.53.3/golangci-lint_1.53.3_linux-arm64.tar.gz"
      sha256 "b9cb1342004be217c5b62ca7baed34550564c49c1b9051d46c01267879a9319e"

      def install
        bin.install "golangci-lint"

        output = Utils.popen_read("#{bin}/golangci-lint completion bash")
        (bash_completion/"golangci-lint").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion fish")
        (fish_completion/"golangci-lint.fish").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
        (zsh_completion/"_golangci-lint").write output

        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/golangci-lint/releases/download/v1.53.3/golangci-lint_1.53.3_linux-amd64.tar.gz"
      sha256 "026afecf85bbda08a6af3ac5506464aaa283597320d20c3bad2d74200340c6f9"

      def install
        bin.install "golangci-lint"

        output = Utils.popen_read("#{bin}/golangci-lint completion bash")
        (bash_completion/"golangci-lint").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion fish")
        (fish_completion/"golangci-lint.fish").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
        (zsh_completion/"_golangci-lint").write output

        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/golangci-lint version"
  end
end
