# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GolangciLint < Formula
  desc "Fast linters runner for Go."
  homepage "https://golangci-lint.octolab.org/"
  version "1.54.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kamilsk/golangci-lint/releases/download/v1.54.2/golangci-lint_1.54.2_darwin-arm64.tar.gz"
      sha256 "412e02388314d815f6501603f8b13bb416887b0e30d21337bf0aae893803879c"

      def install
        bin.install "golangci-lint"

        output = Utils.popen_read("#{bin}/golangci-lint completion bash")
        (bash_completion/"golangci-lint").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion fish")
        (fish_completion/"golangci-lint.fish").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
        (zsh_completion/"_golangci-lint").write output

        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/golangci-lint/releases/download/v1.54.2/golangci-lint_1.54.2_darwin-amd64.tar.gz"
      sha256 "5dbd4c3a3889fb87fbaaf6819fd566177df3751a85bac788e8aaab6592d90d51"

      def install
        bin.install "golangci-lint"

        output = Utils.popen_read("#{bin}/golangci-lint completion bash")
        (bash_completion/"golangci-lint").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion fish")
        (fish_completion/"golangci-lint.fish").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
        (zsh_completion/"_golangci-lint").write output

        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamilsk/golangci-lint/releases/download/v1.54.2/golangci-lint_1.54.2_linux-arm64.tar.gz"
      sha256 "85d9e53053d2c2d7eac0862e291b9143b36802dca9b5129dcf64f66cef9e9b28"

      def install
        bin.install "golangci-lint"

        output = Utils.popen_read("#{bin}/golangci-lint completion bash")
        (bash_completion/"golangci-lint").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion fish")
        (fish_completion/"golangci-lint.fish").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
        (zsh_completion/"_golangci-lint").write output

        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/golangci-lint/releases/download/v1.54.2/golangci-lint_1.54.2_linux-amd64.tar.gz"
      sha256 "6e4e0d9bfdafa8238fa68da77b01901a437e96147cc09252052b8b505baa25a1"

      def install
        bin.install "golangci-lint"

        output = Utils.popen_read("#{bin}/golangci-lint completion bash")
        (bash_completion/"golangci-lint").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion fish")
        (fish_completion/"golangci-lint.fish").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
        (zsh_completion/"_golangci-lint").write output

        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/golangci-lint version"
  end
end
