# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GolangciLint < Formula
  desc "Fast linters runner for Go."
  homepage "https://golangci-lint.octolab.org/"
  version "1.54.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kamilsk/golangci-lint/releases/download/v1.54.0/golangci-lint_1.54.0_darwin-arm64.tar.gz"
      sha256 "a4eac61f4bef35869e7cfbe3c488fed89ad3ba001b974df76a5ffe03e4f2a3ec"

      def install
        bin.install "golangci-lint"

        output = Utils.popen_read("#{bin}/golangci-lint completion bash")
        (bash_completion/"golangci-lint").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion fish")
        (fish_completion/"golangci-lint.fish").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
        (zsh_completion/"_golangci-lint").write output

        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/golangci-lint/releases/download/v1.54.0/golangci-lint_1.54.0_darwin-amd64.tar.gz"
      sha256 "42bf5271f367128e59baab61e8169c50f5879fef0dee9bea8c6e7f5e6cae8db4"

      def install
        bin.install "golangci-lint"

        output = Utils.popen_read("#{bin}/golangci-lint completion bash")
        (bash_completion/"golangci-lint").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion fish")
        (fish_completion/"golangci-lint.fish").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
        (zsh_completion/"_golangci-lint").write output

        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamilsk/golangci-lint/releases/download/v1.54.0/golangci-lint_1.54.0_linux-arm64.tar.gz"
      sha256 "cd4e62c1928a099e75e7e13fe9e90fe9d2c92296738b312183c5d17fc811cdf6"

      def install
        bin.install "golangci-lint"

        output = Utils.popen_read("#{bin}/golangci-lint completion bash")
        (bash_completion/"golangci-lint").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion fish")
        (fish_completion/"golangci-lint.fish").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
        (zsh_completion/"_golangci-lint").write output

        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/golangci-lint/releases/download/v1.54.0/golangci-lint_1.54.0_linux-amd64.tar.gz"
      sha256 "7adfe31297d046e3e7bc8af275a612782568b33051d69e16b4de47a923db5e25"

      def install
        bin.install "golangci-lint"

        output = Utils.popen_read("#{bin}/golangci-lint completion bash")
        (bash_completion/"golangci-lint").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion fish")
        (fish_completion/"golangci-lint.fish").write output

        output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
        (zsh_completion/"_golangci-lint").write output

        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/golangci-lint version"
  end
end
