# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maintainer < Formula
  desc "Maintainer is an indispensable assistant to Open Source contribution."
  homepage "https://github.com/octomation/maintainer"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/octomation/maintainer/releases/download/v0.0.6/maintainer_0.0.6_macOS-64bit_arm.tar.gz"
      sha256 "fcb5678808cc5b30c7a80addd9d1c13afe42f91b0f24b2f85a85ff7d29550db7"

      def install
        bin.install "maintainer"

        output = Utils.popen_read("#{bin}/maintainer completion bash")
        (bash_completion/"maintainer").write output

        output = Utils.popen_read("#{bin}/maintainer completion fish")
        (fish_completion/"maintainer.fish").write output

        output = Utils.popen_read("#{bin}/maintainer completion zsh")
        (zsh_completion/"_maintainer").write output

        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/octomation/maintainer/releases/download/v0.0.6/maintainer_0.0.6_macOS-64bit_x86.tar.gz"
      sha256 "deaff5f431f92f3d0212c1c433f6aa4133a8b8100c7c7c08f03ae602aedc4631"

      def install
        bin.install "maintainer"

        output = Utils.popen_read("#{bin}/maintainer completion bash")
        (bash_completion/"maintainer").write output

        output = Utils.popen_read("#{bin}/maintainer completion fish")
        (fish_completion/"maintainer.fish").write output

        output = Utils.popen_read("#{bin}/maintainer completion zsh")
        (zsh_completion/"_maintainer").write output

        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/octomation/maintainer/releases/download/v0.0.6/maintainer_0.0.6_Linux-64bit_x86.tar.gz"
      sha256 "ac5fd5e6baabcb6ed5270ba1faaaad5a78d0f32a4276881ba939bdcafb7258a0"

      def install
        bin.install "maintainer"

        output = Utils.popen_read("#{bin}/maintainer completion bash")
        (bash_completion/"maintainer").write output

        output = Utils.popen_read("#{bin}/maintainer completion fish")
        (fish_completion/"maintainer.fish").write output

        output = Utils.popen_read("#{bin}/maintainer completion zsh")
        (zsh_completion/"_maintainer").write output

        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/octomation/maintainer/releases/download/v0.0.6/maintainer_0.0.6_Linux-64bit_arm.tar.gz"
      sha256 "0ae39ef6db4ace5cfb8bc90259b52ead13beb25bc3e88ac21bd487bf6405e302"

      def install
        bin.install "maintainer"

        output = Utils.popen_read("#{bin}/maintainer completion bash")
        (bash_completion/"maintainer").write output

        output = Utils.popen_read("#{bin}/maintainer completion fish")
        (fish_completion/"maintainer.fish").write output

        output = Utils.popen_read("#{bin}/maintainer completion zsh")
        (zsh_completion/"_maintainer").write output

        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/maintainer version"
  end
end
