# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maintainer < Formula
  desc "Maintainer is an indispensable assistant to Open Source contribution."
  homepage "https://github.com/octomation/maintainer"
  version "0.0.3"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/octomation/maintainer/releases/download/v0.0.3/maintainer_0.0.3_macOS-64bit.tar.gz"
    sha256 "89fefb929cf1744c3dde1ae45289243540c79cc596f9049a0d13d62336441acb"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/octomation/maintainer/releases/download/v0.0.3/maintainer_0.0.3_Linux-64bit.tar.gz"
    sha256 "b2f6fe800b7481228dbdb342bdcfa25a91dad8e22c42024487a20942bad541ff"
  end

  def install
    bin.install "maintainer"

    output = Utils.popen_read("#{bin}/maintainer completion bash")
    (bash_completion/"maintainer").write output

    output = Utils.popen_read("#{bin}/maintainer completion fish")
    (fish_completion/"maintainer.fish").write output

    output = Utils.popen_read("#{bin}/maintainer completion zsh")
    (zsh_completion/"_maintainer").write output

    prefix.install_metafiles
  end

  test do
    system "#{bin}/maintainer version"
  end
end
