# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Testit < Formula
  desc "Extended testing toolset."
  homepage "https://github.com/octolab/testit"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/octolab/testit/releases/download/v0.2.0/testit_0.2.0_macOS-64bit.tar.gz"
    sha256 "e3e65675fe9ce0c26b114d0fa96cce2258f262b7f155c9b771d990feb3f3d852"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/octolab/testit/releases/download/v0.2.0/testit_0.2.0_Linux-64bit.tar.gz"
    sha256 "de533ea3fe581319dafb2b41a23a23d6ba804b142c0a32f9037469f12be465af"
  end

  def install
    bin.install "testit"

    output = Utils.popen_read("#{bin}/testit completion bash")
    (bash_completion/"testit").write output

    output = Utils.popen_read("#{bin}/testit completion fish")
    (fish_completion/"testit.fish").write output

    output = Utils.popen_read("#{bin}/testit completion zsh")
    (zsh_completion/"_testit").write output

    prefix.install_metafiles
  end

  test do
    system "#{bin}/testit version"
  end
end
