# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Testit < Formula
  desc "Extended testing toolset."
  homepage "https://github.com/octolab/testit"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/octolab/testit/releases/download/v0.1.0/testit_0.1.0_macOS-64bit.tar.gz"
    sha256 "6b8f001b82e926fb086fb57466184d3daec80c827a81d297b54a75d6c58adafd"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/octolab/testit/releases/download/v0.1.0/testit_0.1.0_Linux-64bit.tar.gz"
    sha256 "0613beb6e41549b1124ce8de6434872c86780beec85fb579a823f0b90d334fe2"
  end

  def install
    bin.install "testit"

    output = Utils.popen_read("#{bin}/testit completion bash")
    (bash_completion/"testit").write output

    output = Utils.popen_read("#{bin}/testit completion fish")
    (fish_completion/"testit.fish").write output

    output = Utils.popen_read("#{bin}/testit completion zsh")
    (zsh_completion/"_testit").write output

    prefix.install_metafiles
  end

  test do
    system "#{bin}/testit version"
  end
end
