# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Testit < Formula
  desc "Extended testing toolset."
  homepage "https://github.com/octolab/testit"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/octolab/testit/releases/download/v0.0.1/testit_0.0.1_macOS-64bit.tar.gz"
    sha256 "41cdba4524f1c087d1390bbfd38ea119f6018e3437fa5507c3fd333633fe3395"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/octolab/testit/releases/download/v0.0.1/testit_0.0.1_Linux-64bit.tar.gz"
    sha256 "c8d703c939934926990d5b1b69270177aa4e66f662320c30e3735ffcae113d1a"
  end

  def install
    bin.install "testit"

    output = Utils.popen_read("#{bin}/testit completion bash")
    (bash_completion/"testit").write output

    output = Utils.popen_read("#{bin}/testit completion fish")
    (fish_completion/"testit.fish").write output

    output = Utils.popen_read("#{bin}/testit completion zsh")
    (zsh_completion/"_testit").write output

    prefix.install_metafiles
  end

  test do
    system "#{bin}/testit version"
  end
end
